"""Render an :class:`AnalysisReport` as Markdown."""

from __future__ import annotations

import logging
from typing import List

from ..models import AnalysisReport, FaultAnalysisResult

logger = logging.getLogger(__name__)


def _fmt_list(items: List[str], limit: int = 6) -> str:
    if not items:
        return "_none_"
    shown = items[:limit]
    suffix = "" if len(items) <= limit else f" (+{len(items) - limit} more)"
    return ", ".join(shown) + suffix


def _fault_row(r: FaultAnalysisResult) -> str:
    return "| {obj} | {cls} | {mapped} | {conf} | {inst} | {cell} | {fi} | "\
        "{fo} | {ctrl} | {obsv} | {con} | {scan} | {rc} |".format(
            obj=r.fault.fault_object,
            cls=r.fault.fault_class.value,
            mapped=r.mapping.instance_name or "—",
            conf=r.mapping.confidence.value,
            inst=r.instance_name or "—",
            cell=r.cell_type or "—",
            fi=len(r.fan_in),
            fo=len(r.fan_out),
            ctrl="yes" if r.controllability_issue else "no",
            obsv="yes" if r.observability_issue else "no",
            con="yes" if r.constraint_related else "no",
            scan="yes" if r.scan_boundary_involved else "no",
            rc=r.root_cause.value,
        )


def render_markdown(report: AnalysisReport) -> str:
    """Return a full Markdown document for *report*."""
    s = report.summary
    lines: List[str] = []
    lines.append("# ATPG Coverage-Loss Debug Report")
    lines.append("")
    lines.append("> Generated by **atpg_coverage_debug_agent**. This is a "
                 "structural analysis. Conclusions are heuristic and carry "
                 "confidence/evidence — verify before acting.")
    lines.append("")

    # Executive summary
    lines.append("## Executive Summary")
    lines.append("")
    lines.append(f"- **Total faults analysed:** {s.total_faults}")
    lines.append(f"- **Coverage-loss faults (AU/UO/UC):** {s.coverage_loss_count}")
    lines.append("")
    lines.append("### Fault class counts")
    lines.append("")
    lines.append("| Class | Count |")
    lines.append("| --- | --- |")
    for cls in ("DS", "DI", "TI", "AU", "UO", "UC", "UNKNOWN"):
        if cls in s.class_counts:
            lines.append(f"| {cls} | {s.class_counts[cls]} |")
    lines.append("")

    lines.append("### Top root causes")
    lines.append("")
    if s.top_root_causes:
        lines.append("| Root cause | Count |")
        lines.append("| --- | --- |")
        for name, count in s.top_root_causes:
            lines.append(f"| {name} | {count} |")
    else:
        lines.append("_No coverage-loss faults._")
    lines.append("")

    lines.append("### Top affected instances")
    lines.append("")
    if s.top_instances:
        lines.append("| Instance | Faults |")
        lines.append("| --- | --- |")
        for name, count in s.top_instances:
            lines.append(f"| {name} | {count} |")
    else:
        lines.append("_none_")
    lines.append("")

    lines.append("### Top contributing constraints")
    lines.append("")
    if s.top_constraints:
        lines.append("| Constraint | Faults |")
        lines.append("| --- | --- |")
        for name, count in s.top_constraints:
            lines.append(f"| {name} | {count} |")
    else:
        lines.append("_none detected_")
    lines.append("")

    # Per-fault table
    lines.append("## Per-Fault Detail")
    lines.append("")
    lines.append("| Fault Object | Class | Mapped | Conf | Instance | Cell | "
                 "Fan-in | Fan-out | Ctrl | Obsv | Constr | Scan | Root Cause |")
    lines.append("| --- | --- | --- | --- | --- | --- | --- | --- | --- | "
                 "--- | --- | --- | --- |")
    for r in report.fault_results:
        lines.append(_fault_row(r))
    lines.append("")

    # Evidence detail
    lines.append("## Evidence & Recommendations")
    lines.append("")
    for r in report.fault_results:
        lines.append(f"### {r.fault.fault_object} ({r.fault.fault_class.value})")
        lines.append("")
        lines.append(f"- **Root cause:** {r.root_cause.value}")
        lines.append(f"- **Mapping confidence:** {r.mapping.confidence.value}")
        lines.append(f"- **Observed facts:** {_fmt_list(r.observed_facts)}")
        lines.append(f"- **Inferred conclusions:** "
                     f"{_fmt_list(r.inferred_conclusions)}")
        lines.append(f"- **Evidence:** {_fmt_list(r.evidence)}")
        if r.mapping.candidates:
            lines.append(f"- **Candidate mappings:** "
                         f"{_fmt_list(r.mapping.candidates)}")
        lines.append(f"- **Recommended next step:** {r.recommended_step}")
        lines.append("")

    # Patterns
    lines.append("## Repeated Patterns")
    lines.append("")
    if report.pattern_groups:
        lines.append("| Kind | Key | Count | Sample faults |")
        lines.append("| --- | --- | --- | --- |")
        for g in report.pattern_groups:
            lines.append(f"| {g.kind} | {g.key} | {g.count} | "
                         f"{_fmt_list(g.sample_faults, 3)} |")
    else:
        lines.append("_No repeated patterns detected._")
    lines.append("")

    # Warnings
    lines.append("## Warnings & Limitations")
    lines.append("")
    if report.warnings:
        for w in report.warnings:
            lines.append(f"- {w}")
    else:
        lines.append("_No warnings._")
    lines.append("")

    # Skill Results
    if report.skill_results:
        lines.append("## Skill Results")
        lines.append("")
        for sr in report.skill_results:
            lines.append(f"### {sr.skill_id}")
            lines.append("")
            status = "✓ Success" if sr.success else "✗ Failed"
            lines.append(f"**Status:** {status}")
            lines.append(f"**Summary:** {sr.summary}")
            lines.append("")

            if sr.findings:
                lines.append("#### Findings")
                lines.append("")
                for finding in sr.findings:
                    lines.append(f"- **{finding.title}** [{finding.confidence}]")
                    lines.append(f"  {finding.description}")
                    if finding.evidence:
                        lines.append(f"  Evidence: {', '.join(finding.evidence[:3])}")
                    if finding.recommendation:
                        lines.append(f"  Recommendation: {finding.recommendation}")
                    lines.append("")

            if sr.warnings:
                lines.append("#### Warnings")
                lines.append("")
                for warning in sr.warnings:
                    lines.append(f"- [WARNING] {warning}")
                lines.append("")

    return "\n".join(lines)


def write_markdown(report: AnalysisReport, path: str) -> None:
    """Write the Markdown report to *path*."""
    content = render_markdown(report)
    with open(path, "w", encoding="utf-8") as handle:
        handle.write(content)
    logger.info("Markdown report written to %s", path)
